{% set name = "ilpy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 798b8f32b91306e2ef8b66186e8fc8d519d9f234ba81428ae08184ee97db78fb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("cxx") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
  host:
    - python {{python}}
    - pip
    - cython
    - scip
    - gurobi
  run:
    - python {{python}}
    - scip
    - gurobi

test: 
  imports:
    - ilpy

about:
  home: https://github.com/funkelab/ilpy
  summary: Unified python wrappers for popular ILP solvers
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - tlambert03
    - funkey
