{% set name = "ilpy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6bed753418a60d81894169a9b7b4124e1d2f619d3bb20573fc87de1495d6932c

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("cxx") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython<3.0                            # [build_platform != target_platform]
  host:
    - python {{python}}
    - pip
    - cython<3.0
    - scip=8.1.0
    - gurobi=10.0
  run:
    - python {{python}}
    - scip=8.1.0
    - gurobi=10.0

test: 
  imports:
    - ilpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/funkelab/ilpy
  summary: Unified python wrappers for popular ILP solvers
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
    - funkey
