package:
  name: ilpy
  version: "0.2.1"

source:
  git_url: https://github.com/tlambert03/ilpy
  git_rev: f749d9bc26f358fc6a99a220d4f39a4e803a8edf

build:
  number: 0

requirements:
 build:
   - {{ compiler('cxx') }}
 host:
   - cython
   - python {{python}}
   - scip
   - gurobi
 run:
   - python {{python}}
   - scip
   - gurobi

test: 
  imports:
    - ilpy

about:
  home: https://github.com/funkelab/ilpy
  license: MIT
