{% set name = "ilpy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5cee3c0e5fe6e48cbb4686a8d8362b5e5fa407ab242c480b3981beb7b3429f0c

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("cxx") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython =3.0.9                         # [build_platform != target_platform]
  host:
    - python {{python}}
    - pip
    - cython =3.0.9
    - scip =9.1.0
    - gurobi >=10.0,<12.0
  run:
    - python {{python}}
    - scip =9.1.0
    - gurobi >=10.0,<12.0

test: 
  imports:
    - ilpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/funkelab/ilpy
  summary: Unified python wrappers for popular ILP solvers
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
    - funkey
