package:
  name: ilpy
  version: "0.2.1"

source:
  git_url: https://github.com/funkelab/ilpy/
  git_rev: 0a037d648f1a845ebbbeb5c9d9d6469f03225ccd

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("cxx") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
  host:
    - python {{python}}
    - pip
    - cython
    - scip
    - gurobi
  run:
    - python {{python}}
    - scip
    - gurobi

test: 
  imports:
    - ilpy

about:
  home: https://github.com/funkelab/ilpy
  summary: Unified python wrappers for popular ILP solvers
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - tlambert03
    - funkey
