github:                         
  user_or_org: tlambert03
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - conda-forge
    - gurobi
    - defaults
  # targets is a list of 2-lists, where the first element is the
  # channel to push to and the second element is the label on that channel
  targets:
    - [funkelab, main]
provider:
  linux_64: circle
  osx_64: circle
  win_64: None
  linux_ppc64le: None
  linux_aarch64: None

circle:
  upload_packages: False
