github:                         
  user_or_org: funkelab

channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - gurobi
    - conda-forge
    - defaults
  # targets is a list of 2-lists, where the first element is the
  # channel to push to and the second element is the label on that channel
  targets:
    - [funkelab, main]

# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#provider
provider:
  linux_64: github_actions
  osx_64: github_actions
  win_64: github_actions
  linux_ppc64le: None
  linux_aarch64: None

build_platform:
  osx_arm64: osx_64

test_on_native_only: true

github_actions:
  upload_packages: True
